### ISSUE TITLE
Multiple downloads

### ISSUE THREAD

**Issue by badgone88** [Pool-Of-Tears/Myne#1]
Hello,

Long time i was looking for an app like this one, so thank you !

Do you plan to add possibility to download multiple ebooks by author and language ?

**Comment by starry69** [comment]
You can already downloaded multiple ebooks, do you mean ability to show list of all books by some particular author?

**Comment by badgone88** [comment]
Yes, for example, i would like to download all ebooks from an author.

**Comment by starry69** [comment]
Nice idea, but unfortunately the API I'm using don't have any endpoint to filter the data by author, I'll see what i can do from my end iin future.
