### ISSUE TITLE
What for is usesCleartextTraffic needed?

### ISSUE THREAD

**Issue by IzzySoft** [Pool-Of-Tears/Myne#104]
I've just noticed your app has the `android:usesCleartextTraffic` flag set – which is only needed if you have to access sites without SSL/https. As Gutenberg supports HTTPS, I wonder what for the flag needs to be declared. Can you please shed some light? Thanks in advance!

**Comment by starry-shivam** [comment]
Having this added allows me to do testing in the emulator with gutendex API instance running on localhost. It doesn't cause any trouble for you as a user since release builds use the main API server, which has SSL enabled.

**Comment by IzzySoft** [comment]
If you just need it for local testing, you could also have it enabled with the debug build (for your testing use) while having it removed from the release build (for distribution) – which could be a good compromise.

**Comment by starry-shivam** [comment]
Yeah, I'll remove it with the next commit, please keep this open until then so don't forget about it
