### ISSUE TITLE
[Bug]: Crash on Importing of epub docs on Android 

### ISSUE THREAD

**Issue by Vulciraptor** [Pool-Of-Tears/Myne#105]
### Steps to reproduce

- Go to location of downloaded .epub file, in this case it was internal storage>downloads>MyneEbooks
- open .epub file

### Expected behaviour

Epub file will open and can be read

### Actual behaviour

App crashes immediately 

### Device name

Samsung Galaxy 23

### Android version

Android 14

### Myne version

2.8.0

### Device logs

Build version: 2.8.0 
Current date: 2024-01-26 14:01:32 
Device: Samsung SM-S916U 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.Exception: .opf metadata title tag missing
	at s7.h.l(Unknown Source:862)
	at g9.a.s(Unknown Source:8)
	at ec.f0.run(Unknown Source:112)
	at lc.a.run(Unknown Source:91)
	Suppressed: jc.f: [p1{Cancelling}@8343a91, Dispatchers.IO]

### Additional information

The .epub file was lifted from `https://archive.org/details/RMCG0002`

**Comment by starry-shivam** [comment]
Thanks for reporting, I'll try to investigate it

**Comment by Vulciraptor** [comment]
> Thanks for reporting, I'll try to investigate it

Thank you! If there's anymore information I can provide just let me know.

**Comment by Vulciraptor** [comment]
Sorry did not mean to close this.
