### ISSUE TITLE
[Bug]: Accessibility labels for bottom tab navigation are missing

### ISSUE THREAD

**Issue by schulle4u** [Pool-Of-Tears/Myne#111]
### Steps to reproduce

1. Turn on the TalkBack service in Android accessibility settings. 
2. Open Myne
3. Highlight any of the items in the bottom navigation bar to let TalkBack read their label.

### Expected behaviour

TalkBack should read a useful label for each item, e.g. categories, downloads and settings. 

### Actual behaviour

The screen reader only recognizes a label for the start item. The other items in the navigation are spoken as "unknown" or some nonsense text, in case that automatic icon descriptions are enabled in TalkBack's settings. 

### Device name

Google Pixel 6

### Android version

Android 14

### Myne version

2.9.0

**Comment by starry-shivam** [comment]
Thanks for pointing out, I'll add proper labels for talkback in next release.
