### ISSUE TITLE
[UX enhancement] language sort is hidden when search bar is open

### ISSUE THREAD

**Issue by ludrol** [Pool-Of-Tears/Myne#112]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [X] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

I coudn't find the language button for a while when familarizing myself with UI

Version 2.8.1 from f droid 

The search bar stays open beetween changing states home <-> categories and doesn't reveal the language sort

### Describe the solution you'd like

Language button isn't hidden when searching

Other worse solutions:

Change language on start up and change in the settings

Collapse search bar on screen transitions

### How will you/everyone benefit from this feature?

It will be less confusing on first experience

### Additional context

1) Love the look and the design. 2) Love the name

**Comment by starry-shivam** [comment]
Makes sense, thanks for bringing that to my attention.
