### ISSUE TITLE
Add some indicator of progress for the book such as scroll bar, percentage completed, pages read etc.

### ISSUE THREAD

**Issue by ShramanJain** [Pool-Of-Tears/Myne#118]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [ ] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

The internal reader of the app doesn't give any indication of how far we have progressed within the book.

### Describe the solution you'd like

One of the following:

- percentage of the book that we have read so far
- number of pages that we have read / total no. of pages

### How will you/everyone benefit from this feature?

It will let me and everyone else know how far they have progressed within the book and how much of the book is still left to be read.

### Additional context

The internal reader of the app looks really nice so I would prefer to use it instead lf just switching to some external reader.

**Comment by starry-shivam** [comment]
Good idea, will try in the next update.
