### ISSUE TITLE
[Bug]: Internal reader randomly scrolling to the beginning of the book

### ISSUE THREAD

**Issue by timber-they** [Pool-Of-Tears/Myne#119]
### Steps to reproduce

Sometimes, it feels quite random, the internal reader scrolls to the beginning of the book. Maybe I'm doing something accidently with touch movements, but I wasn't able to reliably reproduce the behavior. It happened twice to me in two days.
This in combination of the lack of a progress indicator makes the internal reader almost unusable for me.

### Expected behaviour

Only scroll to the beginning of the book in well defined cases and don't let such an action be easily triggered on accident.

### Actual behaviour

It scrolls to the beginning of the book unexpectedly.

### Device name

OnePlus 7T

### Android version

LineageOS 21

### Myne version

3.0.0

**Comment by starry-shivam** [comment]
I'll try adding progress indicator, (see #118) and improve the reader bit more in next update.

**Comment by timber-they** [comment]
@starry-shivam the internal reader does indeed seem to be really nice! Thanks for your amazing work <3

**Comment by starry-shivam** [comment]
> @starry-shivam the internal reader does indeed seem to be really nice! Thanks for your amazing work <3

Glad you liked it! & thanks a lot for sponsorship :)

**Comment by timber-they** [comment]
@starry-shivam  Actually the issue isn't solved after all, but I found a more reliable way to reproduce: If long pressing in the reader the first time after opening a book, it scrolls to the beginning of the chapter (instead of merely selecting text). By repeating it this doesm't happen - only text is being selected. However, if the book is closed and opened again, it happens again.
I can send you a screen record, if this description wasn't helpful. However, I suggest to re-open this issue..

**Comment by starry-shivam** [comment]
I see. Thanks for finding a way to reproduce the issue. I've tested it as you described, and yes, I'm able to reproduce the issue. Sorry for the inconvenience. I'll try to fix this in the next release. I've reopened the issue.
