### ISSUE TITLE
Fastlane: per-release changelogs limit

### ISSUE THREAD

**Issue by IzzySoft** [Pool-Of-Tears/Myne#128]
Please be aware that per-release changelogs with Fastlane are limited to 500 chars each – everything behind that limit is simply cut off. Your latest one goes far beyond that, so the last 3 lines won't show up (you were lucky here that char 500 is the last dot of an item, so it's a clear cut – it would be cut mid-word if that's were char 500 is).

For this one, I've simply removed the last 3 lines (they won't show up anyway). For future ones, please make sure to stay in the limit. You can always link to a "full log" if there are too many news :wink:

**Comment by starry-shivam** [comment]
Thanks, I wasn't aware of that. I'll take care of it from next time.

**Comment by starry-shivam** [comment]
Btw, not related to this issue, but is it possible to fix the incorrect screenshots on F-Droid/IzzyOnDroid? I'm just asking to know if there's anything I could do from my end to get this fixed because I see they are still showing old screenshots alongside the new/current ones, even though those old screenshots haven't existed in the Fastlane directory for like a year now

**Comment by IzzySoft** [comment]
> they are still showing old screenshots alongside the new/current ones

Ah, you're talking of F-Droid.org there. Yes, known issue, for years. I gave up hope of seeing that fixed one day, sorry. And no, I cannot help with screenshots there, I'm currently [not active at F-Droid](https://gitlab.com/fdroid/admin/-/issues/447). You'll have to address that there and hope/pray that someone with access to the build/web servers removes them manually.

An alternative that *might* work is having 1x1 px files by the names of the old ones in your Fastlane when F-Droid pulls the next release (and remove those again when that release was published there). If you take that approach, please give me a ping afterwards (when you removed those 1x1 px files again) so I can remove them from my repo again :wink:

**Comment by starry-shivam** [comment]
I see. I guess I'll try the second method first, just to make sure I understand everything clearly. Here's what I need to do:

Before tagging a new release, replace all of the screenshots that are like '1.png', '3.png', '6.png' with some images of size 1x1px (https://onlinepngtools.com/generate-1x1-png) having the same name, i.e., '1.png' to '6.png'.

After F-Droid pulls it (which I don't know how to check or make sure, do you mean when the update gets published on F-Droid?), replace those 1x1px files with the original screenshots like they are right now.

And after that, I'll ping you so you can update them in your repo as well.

Is everything correct?

**Comment by IzzySoft** [comment]
Not quite. `1.png` etc. are your **recent** screenshots which you want to keep. The old ones are `1.jpg` etc. Those are which you want to replace by 1x1 px graphics at F-Droid. So:

* add the 1x1 px JPEG images (`1.jpg` etc) to your fastlane structure just before you make the next release. They would be pulled then by both, F-Droid and my repo's updater.
* wait until that release shows up at F-Droid, verify the old screenshots are gone
* now remove the JPEG files again from your fastlane, then send me a ping so I can take care to have them removed here again

I'm not 100% sure this works, could well be that F-Droid's process would ignore them due to their "unfitting size". But it's worth a try I guess.

**Comment by starry-shivam** [comment]
I see. Thanks for clarifying. Yeah, even if it doesn't work, it doesn't hurt to try once. I'll keep this issue open until then and I'll ping you here once I'm done with it, let's see how it goes :)

**Comment by IzzySoft** [comment]
:crossed_fingers:

**Comment by starry-shivam** [comment]
Hello @IzzySoft looks like your plan worked! However instead of 6 screenshots fdroid is now only showing 5, one of them went missing somehow, but anyways it's still better than previous mess of both old and new screenshots randomly mixed togather 😅

**Comment by IzzySoft** [comment]
> fdroid is now only showing 5

Because there is no `6.png` in your fastlane maybe? :wink: But glad the trick worked out!

**Comment by starry-shivam** [comment]
Oh, you're right. I don't know how I never noticed it. Maybe because they were mixed together with old screenshots, I thought the old one might've overwritten it, anyways thanks for your help! I'll do the same with my orher app too :)

**Comment by IzzySoft** [comment]
Thanks! And as the "dummies" now reached F-Droid, you probably can remove them again. Once done please drop me a note so I can make sure to check it's clean on my end, too.

**Comment by starry-shivam** [comment]
Hello @IzzySoft, I've removed those dummy JPG images in this release. Additionally, I had included the dummy images in my other app's last release, which I'll remove in its next release. Should I ping you whenever I release another version of GreenStash?

**Comment by starry-shivam** [comment]
> Yes please, so I can do the same there then.

@IzzySoft I've removed the dummy images in latest release of GreenStash

**Comment by IzzySoft** [comment]
Thanks! Cleaned them out here as well. Glad to see the trick worked in the expected way, though it's just an ugly work-around…

**Comment by starry-shivam** [comment]
> though it's just an ugly work-around…

Much better than nothing 😄
