### ISSUE TITLE
Add light novel

### ISSUE THREAD

**Issue by OshekharO** [Pool-Of-Tears/Myne#18]
Hii can you please add light novel also: https://github.com/dipu-bd/lightnovel-crawler

**Comment by starry-shivam** [comment]
Hi there! Light novels are currently out of scope for this project, although I'm thinking about adding additional sources for ebooks available under public domain like libgen etc. I may re-think about this in future when I'm done with them and app is mature enough but nor right now, thanks for understanding :)
