### ISSUE TITLE
 [Feature Request] Display navbar when opening menu in reader view 

### ISSUE THREAD

**Issue by zx8418** [Pool-Of-Tears/Myne#203]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [X] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

When I want to quit the reader I have to swipe up to display my phone's navigation bar in order to click system home / back button, which also easily can cause the page to scroll down.

Due to this I have to scroll up most of the times after I return to reading.

### Describe the solution you'd like

The problem could be solved by making navigation bar visible in reader mode menu underneath the font family selection button (SansSerif / Serif)

### How will you/everyone benefit from this feature?

It would save time and effort needed to exit the app and return back to reading at the exact line

**Comment by starry-shivam** [comment]
Thanks for your suggestion! I like this idea, as it will not only simplify navigation but also clear up any confusion some users might have about how to exit the reader. I'll try to implement this before the next release.
