### ISSUE TITLE
Error when opening a epub file 

### ISSUE THREAD

**Issue by mimi89999** [Pool-Of-Tears/Myne#206]
### Steps to reproduce

1. Open the file manager app
2. Click on the file
3. See the error

### Expected behaviour

The app should open the file

### Actual behaviour

The app will show an error

### Device name

Sony Xperia 5 V

### Android version

Android 14

### Myne version

4.0.0

### Device logs

Build version: 4.0.0 
Current date: 2024-09-01 20:52:39 
Device: Sony XQ-DE54 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
P3.p: META-INF/container.xml file missing
	at P3.n.u(Unknown Source:1576)
	at P3.n.o(Unknown Source:12)
	at Y0.a.V(Unknown Source:4)
	at j6.z.z(Unknown Source:73)
	at i4.g.u(Unknown Source:69)
	at C4.a.B(Unknown Source:8)
	at j6.F.run(Unknown Source:112)
	at Y2.c.run(Unknown Source:36)
	at q6.i.run(Unknown Source:2)
	at q6.a.run(Unknown Source:91)
	Suppressed: o6.g: [C{Cancelling}@d17dcfa, Dispatchers.IO]

### Additional information

It's a book I bought online, so I can't share it in the issue.

**Comment by starry-shivam** [comment]
This issue is fixed in #205. Please wait until the next release and try it again. If the issue persists, feel free to reopen it.
