### ISSUE TITLE
[Feature Request] Please clarify the license of the Figerona font

### ISSUE THREAD

**Issue by mimi89999** [Pool-Of-Tears/Myne#208]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [ ] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

I saw that Myne includes the Figerona font (https://github.com/Pool-Of-Tears/Myne/tree/main/app/src/main/res/font). I was searching on the internet and it doesn't seem that this font os published under a free license. I could only find it offered under commercial licenses.

### Describe the solution you'd like

Clarify the license

### How will you/everyone benefit from this feature?

It sill be easier for FOSS app repositories like F-Droid to make sure that the app is entirely free/libre.

**Comment by starry-shivam** [comment]
I downloaded that font from Google Fonts (fonts.google.com), and it's licensed under something called the SIL Open Font License. However, I can't find the Figerona font on Google Fonts right now. I don't really have time to look into this at the moment, as I'd rather focus on clearing the backlog for the next release in my free time. 

FYI, the current font (Figerona) is also not compatible with the Text composables of Jetpack Compose and requires the use of [an additional flag](https://github.com/Pool-Of-Tears/Myne/blob/a711be153a59d063a5b518714452f1194db013df/app/src/main/java/com/starry/myne/ui/theme/Type.kt#L85) to get it working. This flag is a compatibility API and is likely to be deprecated sooner or later, so I'll have to look for a replacement font eventually, but that's not something I can do today. Thanks for understanding.

**Comment by mimi89999** [comment]
I used the `otfinfo` tool to see the info embedded in font:
```
$ otfinfo --info figerona_regular.otf
Family:              Unnamed
Subfamily:           Regular
Full name:           Figerona-Regular
PostScript name:     Figerona-Regular
Preferred family:    Figerona
Version:             Version 1.000
Unique ID:           Version 1.000;PYRS;Figerona-Regular;2021;FL720
Designer:            Drizy Studio
Trademark:           Figerona Trademark of Drizy Studio
Copyright:           Figerona (c) Drizy Studio 2021
Vendor ID:           PYRS
Permissions:         Preview & Print
```

I see that on https://drizystudio.com/figerona-geometric-variable-typeface/ this font is available under a commercial license.

**Comment by licaon-kter** [comment]
So this need https://f-droid.org/docs/Anti-Features/#non-free-assets in F-Droid?

**Comment by starry-shivam** [comment]
> So this need https://f-droid.org/docs/Anti-Features/#non-free-assets in F-Droid?

You can add it if you think it's necessary, I'm not prioritizing it right now. As I mentioned, this font will be replaced with something else, probably a similar-looking font, after a few Compose releases when they drop this compatibility API, which will render this font unusable anyway. However, that day is not today.

**Comment by mimi89999** [comment]
If you are willing to accept my contribution, I can find a similar font and open a Pull request with a commit replacing that font.

**Comment by starry-shivam** [comment]
> If you are willing to accept my contribution, I can find a similar font and open a Pull request with a commit replacing that font.

Please keep in mind that some UI elements, like the read/delete buttons on the library screens and the padding of various components, might also need adjustment when changing the font. But yes, I’m not against it, and I’ll try to fix those later after merging if necessary. I think you can try the Poppins font from the Google Fonts website it looks pretty good, imo.
