### ISSUE TITLE
[Feature Request] Please clarify the license of lottie animation files

### ISSUE THREAD

**Issue by mimi89999** [Pool-Of-Tears/Myne#209]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [ ] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

Please clarify the license of the lottie animation files in https://github.com/Pool-Of-Tears/Myne/tree/main/app/src/main/res/raw . I couldn't find any info about them on the internet.

### Describe the solution you'd like

Clarify the license

### How will you/everyone benefit from this feature?

It sill be easier for FOSS app repositories like F-Droid to make sure that the app is entirely free/libre.

**Comment by starry-shivam** [comment]
Some lottie animations are designed by me and my one friend, others are taken from https://lottiefiles.com/, you can read about their license here https://lottiefiles.com/page/license
