### ISSUE TITLE
[Bug]: Render problem

### ISSUE THREAD

**Issue by jcafranca** [Pool-Of-Tears/Myne#233]
### Steps to reproduce

Their was always render problem, its in the viewmodel dont know how to fix. please help. Thanks.

### Expected behaviour

Good

### Actual behaviour

Good

### Device name

Pixel 5

### Android version

Android 8.0

### Myne version

4.3.0

**Comment by starry-shivam** [comment]
> Expected behaviour
> Good

> Actual behaviour
> Good

What?! Sorry, but what's the problem then? 

> Their was always render problem, its in the viewmodel dont know how to fix

What does that even mean? I'm not an all-knowing, omniscient figure who can read your mind to figure out the exact problem you're facing if you don't provide the slightest clue about it.. 

Closing. Feel free to reopen once you provide enough details, as it's a completely pointless issue in its current form.
