### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [Pool-Of-Tears/Myne#29]
Please add support the Android 13 Themed Icons.

![Screenshot_2023-02-25-03-02-39-570_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/221321629-a3ee1bc4-1fc7-4615-b40f-85e4f043ddac.jpg)

**Comment by starry-shivam** [comment]
Good idea, will do in the next release.

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by xmha97** [comment]
Thanks 🙏
