### ISSUE TITLE
TTS

### ISSUE THREAD

**Issue by Pantyhose-X** [Pool-Of-Tears/Myne#31]
Through the system TTS engine, read the book aloud

**Comment by hyper-ub** [comment]
@Pantyhose-X Pro

**Comment by starry-shivam** [comment]
Sorry, but that's currently out of scope for this project, myne is primarily an _ebook downloader_, not a full fledged ebook reader app, I just added a minimal inbuilt reader cause few people suggested this kind of app looks kinda half baked without any reader at all, but if you need advanced features (like TTS for example) please consider using some dedicated ebook reader application like google play books and similar, that's also one of the reason why i kept internal reader disabled by default as it might be too barebones for most people out there.

**Comment by hyper-ub** [comment]
@starry-shivam 👍

**Comment by hyper-ub** [comment]
@hyper-ub Tf.

**Comment by ThreeDeeJay** [comment]
ReadEra is a petty neat external reader with android TTS engine support. I even got out running Ivona TTS I Android 13 (old but gold)
