### ISSUE TITLE
Failure to download books with forbidden characters in title 

### ISSUE THREAD

**Issue by palopezv** [Pool-Of-Tears/Myne#33]
When you try to download a book with filesystem forbidden characters in its name. And it keeps trying and trying. An example _Oscar Wilde's The Importance of Being Earnest: A Trivial Comedy for Serious People_.

The link is: https://www.gutenberg.org/ebooks/844

**Comment by starry-shivam** [comment]
@palopezv Can confirm, thanks for submitting an issue, will try to fix it in the next release.
