### ISSUE TITLE
External book

### ISSUE THREAD

**Issue by EnchantedGoldenApple** [Pool-Of-Tears/Myne#40]
If it is possible, add opportunity to open epub, fb2, or other formats. All these formats contain metadata to display names, authors, and book covers.

**Comment by starry-shivam** [comment]
Not sure about fb2 (as idk much about this format and the app cannot parse it), but i will try to add support for opening external epub files in future.. thanks for suggestion.

**Comment by lokomoto** [comment]
Currently if you reinstall the app or clear it's data, the books remain in the download folder but the app is not able to detect them. Adding a rescan button could solve this problem and also serve as a way to add external epubs to the library.

**Comment by tjsuominen** [comment]
Any progress on opening / importing epub files from e.g. Google drive?

**Comment by starry-shivam** [comment]
> Any progress on opening / importing epub files from e.g. Google drive?

Currently not any plans for Google drive support, but I'll try if it's easy enough when adding support for importing local epub books, bit busy these days with some personal stuff.

**Comment by Myzel394** [comment]
How do you open external books? I can't figure it out :/

**Comment by starry-shivam** [comment]
> How do you open external books? I can't figure it out :/


https://github.com/Pool-Of-Tears/Myne/assets/58552395/7e5e0258-d6a2-4674-a26d-fb0aa82bded6

Like this

**Comment by Myzel394** [comment]
Ahh I see, doesn't seem to be working with pdfs though?

**Comment by starry-shivam** [comment]
> Ahh I see, doesn't seem to be working with pdfs though?

The app only supports epubs.
