### ISSUE TITLE
Additional sources

### ISSUE THREAD

**Issue by rhynec** [Pool-Of-Tears/Myne#44]
Standard Ebooks provides project gutenberg books with standardized formatting, various editorial tweaks, and rich metadata. They also provide OPDS feeds to browse their collection. Apparently, this is locked behind a Patreon donation, but Foliate sources from SE so I assume they make an exception for FOSS projects.

Link: https://standardebooks.org/

**Comment by rhynec** [comment]
There's also Feedbooks which provides an OPDS feed for public domain works.

Link: https://www.feedbooks.com/catalog/public_domain

**Comment by starry-shivam** [comment]
> so I assume they make an exception for FOSS projects.

Sorry, but I haven't been able to find anything related to this on their website, they also require sign-in to read/parse feeds which means I'll need to hardcode my credentials in the app for it to work or ask users to sign-in with their credentials which is too much work and not really worth it imo..
