### ISSUE TITLE
Option to change the default storage location of the downloaded files

### ISSUE THREAD

**Issue by senntore** [Pool-Of-Tears/Myne#48]
As title suggest, It would be nice if it can be implemented or atleast change the default storage location to somewhere in Home directory(or whatever it's called in android) rather than in Download or Documents.
I request this because I sync them to another system with syncthing & don't want directories that don't use regularly to be in there, since the books can be read from inside Myne & we can always copy the files if we need them somewhere else.

**Comment by starry-shivam** [comment]
Thing is, starting Android 12 unless you have `MANAGE_EXTERNAL_STORAGE` permission (permission to access all of the files on device like file manager apps), Android don't allow apps to write data anywhere (i.e. in home directory) except standerd system directories, like music/document/photo/download etc, and Android 13 even removed the permission `READ/WRITE_EXTERNAL_STORAGE`, and introduced more granular permissions like `READ_MEDIA_AUDIO` for accessing system music directory, `READ_MEDIA_PHOTO` for accessing system photos directory etc, and there is no permission available which allows apps to write data directly in the home directory, so basically it's very hard or almost impossible to implement without targeting to lower sdks like API 30 or so.. which ofcourse isn't an option if i want app to utilise latest APIs and function properly on morden devices.

Thanks for understanding :)

**Comment by AceDenghar** [comment]
I understand your explanation but it could be a great feature....

I really would like to use a folder on a sdcard to save ebooks and, like senntore, sync them with my other android device (with foldersync)...

**Comment by ThreeDeeJay** [comment]
Don't the latest Androids allow (or rather, force) apps to use the built-in file browser to select a folder anywhere (internal or external SD storage) to be able to write to it?
It does have some limitations like not being able to use a root/non-empty folder for security reasons, but that shouldn't be a hurdle for this specific purpose  🤔

**Comment by starry-shivam** [comment]
> Don't the latest Androids allow (or rather, force) apps to use the built-in file browser to select a folder anywhere (internal or external SD storage) to be able to write to it? It does have some limitations like not being able to use a root/non-empty folder for security reasons, but that shouldn't be a hurdle for this specific purpose 🤔

Yeah, but at that time i had more important stuff to implement (as the app was very new & lot of other things needed work) than to research/lookup about that, and the usual method i knew to implement something like this this (by getting READ/WRITE_EXTERNAL_STORAGE permission) was no longer working in latest android versions so i skipped it that time, I'll try again with the new scoped storage folder permission method, if i get enough time to work on it. I'm not getting much time to work on my personal projects recently due to my job & I'm too tired on Sunday to do anything :( Let's see when it happens..

**Comment by ThreeDeeJay** [comment]
Oh I totally get you mate. It's not really a huge deal anyway, but I'll keep an eye on this thread on case it gets implemented eventually 🤞🙂
