### ISSUE TITLE
Myne 1.4.0 Crashes immediately - 2 different fones

### ISSUE THREAD

**Issue by Snord9** [Pool-Of-Tears/Myne#49]
Myne 1.4.0 Crashes almost immediately

Activity swirl for a second or 3 .. then crash
Tried tapping on different bottom buttons Home ___ Library ___,
 no  difference.

2 different fones:

Sams s5 andriod 6.0.1

MotoEdge2022 andriod 12

**Comment by starry-shivam** [comment]
Please update to latest version 1.7.0 and share logcat if problem persists.

**Comment by Snord9** [comment]
F-droid only offers v 1.4.0
I am not interested in fetching from gPlayStore 
(where it appears to cost $2.49 =non- FOSS)

Thanks, anyway.
The UI did look attractive.

**Comment by starry-shivam** [comment]
> where it appears to cost $2.49 =non- FOSS

Gplay version is exactly same as any other version, costing some amount doesn't makss it non-foss, the F in FOSS means "free as in freedom, not free as in price" besides you can always grab latest version from [GitHub release](https://github.com/Pool-Of-Tears/Myne/releases/tag/v1.7.0) it won't cost you anything, the play store version is for people who would like to support the development by contributing some amount (i.e. by buying from gplay) and in return will also get something like easy automatic updates directly from Google Play without downloading and installing apk by themselves, but you ofcourse don't need to pay/buy anything if you don't wish to.

**Comment by starry-shivam** [comment]
> Sams s5 andriod 6.0.1
Btw app is not compatible with Android 6.0, it's clearly written in the Readme that it's only compatible with Android 7.0 and later.

**Comment by Snord9** [comment]
DATE 2023-03-25, Saturday

F-droid [today] offers v 1.4.0, dated = Mar.11
which was encouraging, a few days back, when I first installed.
BUT..
PlayStore [today] offers the app DATE DIFFERENT = Mar.24 (version unclear)

I help people who rely on adaptive aids. 
I only recommend/specify FOSS for them which is practical to install, as I support them "over-the-phone".
SO .. 
I may come back in a week or so, to see if F-droid's version is 1.7.x

Thank you for your work. 
I am unlikely to get back into programming, but you have sparked an interest in Kotlin, here.

smiles from Canada :--)

**Comment by starry-shivam** [comment]
Sure no problem, closing the issue for now, feel free to re-open if you're still having problems in future.
