### ISSUE TITLE
[Feature Request] Font Family

### ISSUE THREAD

**Issue by bloodyeyesblackblood** [Pool-Of-Tears/Myne#61]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [ ] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

i think the default reading font is terrible, at least it's hard to read for me.

### Describe the solution you'd like

more Font Family like Inter, OpenDylexia, Arial and Device Fonts.

### How will you/everyone benefit from this feature?

Customizabilty, some can just use the font that works the best for them. / Better Readabilty.

**Comment by starry-shivam** [comment]
Yeah, I've plans to add more font choices in the reader, I'm bit busy right now days due to personal reasons will try this in upcoming updates.
