### ISSUE TITLE
[Feature Request] Keep language selection 

### ISSUE THREAD

**Issue by AceDenghar** [Pool-Of-Tears/Myne#67]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [ ] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

Language selection is  not kept while the app is relaunched

### Describe the solution you'd like

I would like that language selection could be maintained between different sessions

### How will you/everyone benefit from this feature?

We would not have to change the selection everytime we use the app

### Additional context

Thanks for job already done !

(And sorry for my English)

**Comment by starry-shivam** [comment]
Seems like a good idea, will think about it.
