### ISSUE TITLE
[Bug]: "Material You" button flashes

### ISSUE THREAD

**Issue by Cwpute** [Pool-Of-Tears/Myne#81]
### Steps to reproduce

1. have ane Android 11 device
2. tap the "Material You" button in the options
3. see bug

### Expected behaviour

The message (i believe it's called a toast box or something ?) should stay long enough on the screen for the user to read it.

### Actual behaviour

A message appears for a flash second while the button is seemingly activated, but disapears as soon as the button appears to revert back to its inactivated state.

### Android version

Android 11

### Myne version

1.5.0

### Additional information

It might be because the message is automatically hidden when the app "reverts" back the buton and UI to its previous state, although it didn't change the UI to begin with.

**Comment by Cwpute** [comment]
@starry-shivam 
https://github.com/Pool-Of-Tears/Myne/assets/80604512/f96b9681-4d6b-4671-8278-0bca89e72de7

**Comment by starry-shivam** [comment]
Thanks, I'll try to fix it in next release
