### ISSUE TITLE
[Bug]: When I want to read a book I got error

### ISSUE THREAD

**Issue by MahdiRahmani80** [Pool-Of-Tears/Myne#94]
### Steps to reproduce

1. when click on book (Home, Search)
2. Go to new page (waiting page)
3. vanish waiting page
3. did not shown the book page and I have a `restart app` error like the picture

 <img src="https://github.com/Pool-Of-Tears/Myne/assets/64958072/73724eca-66b6-41bb-845e-5952dfccdef3" alt="drawing" width="80"/>

### Expected behaviour

show the `book screen` for reading

## I sow this
for every books I take this error
 <img src="https://github.com/Pool-Of-Tears/Myne/assets/64958072/73724eca-66b6-41bb-845e-5952dfccdef3" alt="drawing" width="150"/>

### Device name

Xiaomi M2010J19CI 

### Android version

Android 12

### Myne version

2.6.0 

### Device logs

```
Build version: 2.6.0 
Current date: 2023-11-06 18:54:23 
Device: Xiaomi M2010J19CI 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
 at org.json.JSON.typeMismatch(JSON.java:112)
 at org.json.JSONObject.<init>(JSONObject.java:172)
 at org.json.JSONObject.<init>(JSONObject.java:185)
 at q7.j.f(Unknown Source:7)
 at q7.d.a(Unknown Source:23)
 at kc.g.run(Unknown Source:42)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at java.lang.Thread.run(Thread.java:1012)
```

**Comment by starry-shivam** [comment]
Unfortunately I'm not able to reproduce the error you're facing.
![](https://te.legra.ph/file/43d696464a13412d2e264.jpg)

Can you please tell some more details like which version you're using? Google play/f-droid and your carrier/ISP name?

**Comment by starry-shivam** [comment]
Closing due to no response in a long time, feel free to reopen if you're still facing the issue.
